In [1]:
import pandas as pd
zip_codes = pd.read_csv("zip_code_database.csv")
zip_codes.head()

,zip,type,decommissioned,primary_city,acceptable_cities,unacceptable_cities,state,county,timezone,area_codes,world_region,country,latitude,longitude,irs_estimated_population
0,501,UNIQUE,0,Holtsville,NaN,Internal Revenue Service,NY,Suffolk County,America/New_York,631,NaN,US,40.81,-73.04,562
1,544,UNIQUE,0,Holtsville,NaN,Internal Revenue Service,NY,Suffolk County,America/New_York,631,NaN,US,40.81,-73.04,0
2,601,STANDARD,0,Adjuntas,NaN,"Colinas Del Gigante, Jard De Adjuntas, Urb San...",PR,Adjuntas Municipio,America/Puerto_Rico,"787, 939",NaN,US,18.16,-66.72,0
3,602,STANDARD,0,Aguada,NaN,"Alts De Aguada, Bo Guaniquilla, Comunidad Las ...",PR,Aguada Municipio,America/Puerto_Rico,"787, 939",NaN,US,18.38,-67.18,0
4,603,STANDARD,0,Aguadilla,Ramey,"Bda Caban, Bda Esteves, Bo Borinquen, Bo Ceiba...",PR,Aguadilla Municipio,America/Puerto_Rico,"787, 939",NaN,US,18.43,-67.15,0

In [2]:
ca_zip_codes = zip_codes[zip_codes["state"] == "CA"]
ca_zip_codes.head()

,zip,type,decommissioned,primary_city,acceptable_cities,unacceptable_cities,state,county,timezone,area_codes,world_region,country,latitude,longitude,irs_estimated_population
38211,90001,STANDARD,0,Los Angeles,"Firestone Park, Firestone Pk",NaN,CA,Los Angeles County,America/Los_Angeles,"213, 323",NaN,US,33.97,-118.24,50130
38212,90002,STANDARD,0,Los Angeles,Watts,NaN,CA,Los Angeles County,America/Los_Angeles,"213, 310, 323, 424",NaN,US,33.94,-118.24,45910
38213,90003,STANDARD,0,Los Angeles,NaN,Broadway Manchester,CA,Los Angeles County,America/Los_Angeles,"213, 323",NaN,US,33.96,-118.27,62560
38214,90004,STANDARD,0,Los Angeles,Oakwood,NaN,CA,Los Angeles County,America/Los_Angeles,"213, 323",NaN,US,34.07,-118.31,46770
38215,90005,STANDARD,0,Los Angeles,Sanford,NaN,CA,Los Angeles County,America/Los_Angeles,"213, 323",NaN,US,34.06,-118.31,28000

In [3]:
la_zip_codes = ca_zip_codes[ca_zip_codes["primary_city"] == "Los Angeles"]
la_zip_codes

,zip,type,decommissioned,primary_city,acceptable_cities,unacceptable_cities,state,county,timezone,area_codes,world_region,country,latitude,longitude,irs_estimated_population
38211,90001,STANDARD,0,Los Angeles,"Firestone Park, Firestone Pk",NaN,CA,Los Angeles County,America/Los_Angeles,"213, 323",NaN,US,33.97,-118.24,50130
38212,90002,STANDARD,0,Los Angeles,Watts,NaN,CA,Los Angeles County,America/Los_Angeles,"213, 310, 323, 424",NaN,US,33.94,-118.24,45910
38213,90003,STANDARD,0,Los Angeles,NaN,Broadway Manchester,CA,Los Angeles County,America/Los_Angeles,"213, 323",NaN,US,33.96,-118.27,62560
38214,90004,STANDARD,0,Los Angeles,Oakwood,NaN,CA,Los Angeles County,America/Los_Angeles,"213, 323",NaN,US,34.07,-118.31,46770
38215,90005,STANDARD,0,Los Angeles,Sanford,NaN,CA,Los Angeles County,America/Los_Angeles,"213, 323",NaN,US,34.06,-118.31,28000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38306,90101,STANDARD,1,Los Angeles,NaN,"Bulk Mail Center, La",CA,Los Angeles County,America/Los_Angeles,213,NaN,US,33.99,-118.16,0
38307,90102,UNIQUE,1,Los Angeles,Brylane,NaN,CA,Los Angeles County,America/Los_Angeles,213,NaN,US,34.01,-118.19,0
38308,90103,UNIQUE,1,Los Angeles,NaN,Rodale Press,CA,Los Angeles County,America/Los_Angeles,213,NaN,US,33.99,-118.16,0
38309,90134,STANDARD,0,Los Angeles,NaN,Goat,CA,Los Angeles County,America/Los_Angeles,"213, 323",NaN,US,34.05,-118.25,0
38310,90189,UNIQUE,0,Los Angeles,NaN,"Citibank, First Data Remitco",CA,Los Angeles County,America/Los_Angeles,213,NaN,US,34.06,-118.25,0

In [4]:
# saving LA zip codes as a CSV file
la_zip_codes.to_csv("la_zip_codes.csv")

In [5]:
la_county_zip_codes = ca_zip_codes[ca_zip_codes["county"] == "Los Angeles County"]
print(len(la_county_zip_codes))
la_county_zip_codes.head()

528

,zip,type,decommissioned,primary_city,acceptable_cities,unacceptable_cities,state,county,timezone,area_codes,world_region,country,latitude,longitude,irs_estimated_population
38211,90001,STANDARD,0,Los Angeles,"Firestone Park, Firestone Pk",NaN,CA,Los Angeles County,America/Los_Angeles,"213, 323",NaN,US,33.97,-118.24,50130
38212,90002,STANDARD,0,Los Angeles,Watts,NaN,CA,Los Angeles County,America/Los_Angeles,"213, 310, 323, 424",NaN,US,33.94,-118.24,45910
38213,90003,STANDARD,0,Los Angeles,NaN,Broadway Manchester,CA,Los Angeles County,America/Los_Angeles,"213, 323",NaN,US,33.96,-118.27,62560
38214,90004,STANDARD,0,Los Angeles,Oakwood,NaN,CA,Los Angeles County,America/Los_Angeles,"213, 323",NaN,US,34.07,-118.31,46770
38215,90005,STANDARD,0,Los Angeles,Sanford,NaN,CA,Los Angeles County,America/Los_Angeles,"213, 323",NaN,US,34.06,-118.31,28000